# Goal: Main Branch Pipeline 

name: Main Pipeline

on:
    push:
        branches:
            - main 

jobs:
    build-and-test:
        uses: ./.github/workflows/reusable-build-test.yml
        with:
            run_tests: true
            working-directory: './backend'

    build-and-push-docker:
        needs: build-and-test
        uses: ./.github/workflows/reusable-docker.yml
        with:
            image-name: 'rashidkhan6685/devboard-backend'
            tag: 'latest'
            working-directory: './backend'
        secrets:
            docker_username: ${{ secrets.DOCKER_USERNAME }}
            docker_password: ${{ secrets.DOCKER_PASSWORD }}

    security-scan:
        needs: build-and-push-docker
        runs-on: ubuntu-latest
        steps:
            - name: Run Trivy Vulnerability Scanner
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: 'rashidkhan6685/devboard-backend:latest'
                format: 'table'
                output: 'trivy-report.txt'
                exit-code: '1'
                severity: 'CRITICAL'
            
            - name: Upload Trivy Scan Report
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: trivy-security-report
                path: trivy-report.txt

    deploy:
        needs: security-scan
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout Code
              uses: actions/checkout@v7

            - name: Copy files to EC2 via SCP
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_SSH_KEY }}
                source: "docker-compose.yml,init/postgres/,.env.example"
                target: "/home/ubuntu/devboard-app"

            - name: Execute Deployment on EC2 via SSH
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                    cd /home/ubuntu/devboard-app

                    # 2. README step: Settings live in .env
                    cp .env.example .env

                    # 3. pull the latest image from Docker hub
                    docker compose pull

                    # 4. Run the container in background (detached mode)
                    docker compose up -d

                    # 5. Deletes the unused and older images so ec2 storage wonnot full.
                    docker image prune -af


