# Goal: Main Branch Pipeline 

name: Main Pipeline

on:
    push:
        branches:
            - main 

jobs:
    build-and-test:
        uses: ./.github/workflows/reusable-build-test.yml
        with:
            run_tests: true
            working-directory: './backend'

    build-and-push-docker:
        needs: build-and-test
        uses: ./.github/workflows/reusable-docker.yml
        with:
            image-name: 'rashidkhan6685/devboard-backend'
            tag: 'latest'
            working-directory: './backend'
        secrets:
            docker_username: ${{ secrets.DOCKER_USERNAME }}
            docker_password: ${{ secrets.DOCKER_PASSWORD }}

    security-scan:
        needs: build-and-push-docker
        runs-on: ubuntu-latest
        steps:
            - name: Run Trivy Vulnerability Scanner
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: 'rashidkhan6685/devboard-backend:latest'
                format: 'table'
                output: 'trivy-report.txt'
                exit-code: '1'
                severity: 'CRITICAL'
            
            - name: Upload Trivy Scan Report
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: trivy-security-report
                path: trivy-report.txt

    deploy:
        name: Production Deployment 
        needs: security-scan
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Trigger Deployment
              run: |
                echo "Deploying image: ${{ needs.build-and-push-docker.outputs.image_url }} to production"