# Goal: Main Branch Pipeline 

name: Main Pipeline

on:
    push:
        branches:
            - main 

jobs:
    build-and-test:
        uses: ./.github/workflows/reusable-build-test.yml
        with:
            run_tests: true
            working-directory: './backend'

    build-and-push-docker:
        needs: build-and-test
        uses: ./.github/workflows/reusable-docker.yml
        with:
            image-name: 'rashidkhan/devboard-backend'
            tag: 'latest'
            working-directory: './backend'
        secrets:
            docker_username: ${{ secrets.DOCKER_USERNAME }}
            docker_password: ${{ secrets.DOCKER_PASSWORD }}

    deploy:
        name: Production Deployment 
        needs: build-and-push-docker
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Trigger Deployment
              run: |
                echo "Deploying image: ${{ needs.build-and-push-docker.outputs.image_url }} to production"